language: python
cache:
  pip: true
  directories:
    - .tox
    - /home/travis/.cargo/bin
    - server
sudo: required
dist: trusty
install:
  - sudo apt-get -qq update
  - sudo add-apt-repository -y ppa:jonathonf/rustlang
  - sudo apt-get install -y lua5.1 liblua5.1-0-dev cargo
  - if [ ! -d "server/target/debug" ]; then git clone https://github.com/braidery/braid.git server && cd server && cargo build; fi
  - pip install tox nose requests
script:
  - tox
env:
  global:
    - PATH=server/target/debug:$PATH
  matrix:
    - TOXENV=py2
    - TOXENV=py3
    - TOXENV=pypy
