# Language is rust because we depend on spinning up the server to run tests,
# and it's easier to get python up and running in a rust test environment than
# the other way around in TravisCI.
language: rust
cache:
  pip: true
  directories:
    - .tox
    - server
sudo: required
dist: trusty
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y lua5.1 liblua5.1-0-dev python3
  - if [ ! -d "server/target/debug" ]; then git clone https://github.com/indradb/indradb.git server && pushd server && cargo build && popd; fi
  - pip3 install tox nose requests
script:
  - tox
env:
  global:
    - PATH=server/target/debug:$PATH
  matrix:
    - TOXENV=py2
    - TOXENV=py3
    - TOXENV=pypy
