language: python
cache:
  pip: true
  directories:
    - .tox
    - /home/travis/.cargo/bin
sudo: required
dist: trusty
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y lua5.1 liblua5.1-0-dev
  - curl https://sh.rustup.rs -sSf > rustup-init
  - chmod +x rustup-init
  - ./rustup-init -y
  - rustc --version
  - cargo --version
  - git clone https://github.com/braidery/braid.git server
  - cd server && cargo build
  - pip install tox
script:
  - tox
env:
  global:
    - PATH=server/target/debug:/home/travis/.cargo/bin:$PATH
  matrix:
    - TOXENV=py2
    - TOXENV=py3
    - TOXENV=pypy
