# Language is rust because we depend on spinning up the server to run tests,
# and it's easier to get python up and running in a rust test environment than
# the other way around in TravisCI.
language: rust
cache:
  pip: true
  directories:
    - .tox
    - server
    - venv
sudo: required
dist: trusty
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y lua5.1 liblua5.1-0-dev python3
  - if [ $TOXENV = pypy ]; then sudo apt-get install -y pypy; fi
  - if [ ! -d "server/target/debug" ]; then git clone https://github.com/indradb/indradb.git server && pushd server && cargo build && popd; fi
  - virtualenv -p python3 venv && source venv/bin/activate && pip install tox nose requests
script:
  - source venv/bin/activate && tox
env:
  global:
    - PATH=server/target/debug:$PATH
  matrix:
    - TOXENV=py2
    - TOXENV=py3
    - TOXENV=pypy
